<a href="https://colab.research.google.com/github/anwarkhan119/Heart-Disease-Data-Analysis/blob/main/Product_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.13/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets) (3.32.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.1.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (1.27.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.24.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [ ]:
from datasets import load_dataset

dataset = load_dataset(
    "McAuley-Lab/Amazon-Reviews-2023",
    "raw_meta_All_Beauty",
    split="full"
)

print(dataset)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/30.3k [00:00<?, ?B/s]

Amazon-Reviews-2023.py:   0%|          | 0.00/39.6k [00:00<?, ?B/s]

RuntimeError: Dataset scripts are no longer supported, but found Amazon-Reviews-2023.py

In [ ]:
from datasets import load_dataset

url = "https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw_meta_All_Beauty/full-00000-of-00001.parquet"

dataset = load_dataset("parquet", data_files=url, split="train")

print(dataset)

raw_meta_All_Beauty/full-00000-of-00001.(…): reconstructing file:   0%|          |  0.00B / 59.6MB

raw_meta_All_Beauty/full-00000-of-00001.(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together', 'subtitle', 'author'],
    num_rows: 112590
})

In [ ]:
import pandas as pd
df=pd.DataFrame(dataset)
print(df.shape)

(112590, 16)

In [ ]:
df.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Beauty,"Howard LC0008 Leather Conditioner, 8-Ounce (4-...",4.8,10,[],[],None,"{'hi_res': [None, 'https://m.media-amazon.com/...","{'title': [], 'url': [], 'user_id': []}",Howard Products,[],"{""Package Dimensions"": ""7.1 x 5.5 x 3 inches; ...",B01CUPMQZE,None,None,None
1,All Beauty,Yes to Tomatoes Detoxifying Charcoal Cleanser ...,4.5,3,[],[],None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Yes To,[],"{""Item Form"": ""Powder"", ""Skin Type"": ""Acne Pro...",B076WQZGPM,None,None,None
2,All Beauty,Eye Patch Black Adult with Tie Band (6 Per Pack),4.4,26,[],[],None,"{'hi_res': [None, None], 'large': ['https://m....","{'title': [], 'url': [], 'user_id': []}",Levine Health Products,[],"{""Manufacturer"": ""Levine Health Products""}",B000B658RI,None,None,None
3,All Beauty,"Tattoo Eyebrow Stickers, Waterproof Eyebrow, 4...",3.1,102,[],[],None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Cherioll,[],"{""Brand"": ""Cherioll"", ""Item Form"": ""Powder"", ""...",B088FKY3VD,None,None,None
4,All Beauty,Precision Plunger Bars for Cartridge Grips – 9...,4.3,7,"[Material: 304 Stainless Steel; Brass tip, Len...",[The Precision Plunger Bars are designed to wo...,None,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Precision,[],"{""UPC"": ""644287689178""}",B07NGFDN6G,None,None,None

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112590 entries, 0 to 112589
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   main_category    112590 non-null  object
 1   title            112590 non-null  object
 2   average_rating   112590 non-null  float64
 3   rating_number    112590 non-null  int64
 4   features         112590 non-null  object
 5   description      112590 non-null  object
 6   price            112590 non-null  object
 7   images           112590 non-null  object
 8   videos           112590 non-null  object
 9   store            101259 non-null  object
 10  categories       112590 non-null  object
 11  details          112590 non-null  object
 12  parent_asin      112590 non-null  object
 13  bought_together  0 non-null       object
 14  subtitle         0 non-null       object
 15  author           0 non-null       object
dtypes: float64(1), int64(1), object(14)
memory usage: 13.7+ MB

In [ ]:
df.isnull().sum()

main_category           0
title                   0
average_rating          0
rating_number           0
features                0
description             0
price                   0
images                  0
videos                  0
store               11331
categories              0
details                 0
parent_asin             0
bought_together    112590
subtitle           112590
author             112590
dtype: int64

In [ ]:
products = df[
    [
        "title",
        "average_rating",
        "rating_number",
        "features",
        "description",
        "price",
        "store",
        "categories"
    ]
].copy()

products.head()

,title,average_rating,rating_number,features,description,price,store,categories
0,"Howard LC0008 Leather Conditioner, 8-Ounce (4-...",4.8,10,[],[],None,Howard Products,[]
1,Yes to Tomatoes Detoxifying Charcoal Cleanser ...,4.5,3,[],[],None,Yes To,[]
2,Eye Patch Black Adult with Tie Band (6 Per Pack),4.4,26,[],[],None,Levine Health Products,[]
3,"Tattoo Eyebrow Stickers, Waterproof Eyebrow, 4...",3.1,102,[],[],None,Cherioll,[]
4,Precision Plunger Bars for Cartridge Grips – 9...,4.3,7,"[Material: 304 Stainless Steel; Brass tip, Len...",[The Precision Plunger Bars are designed to wo...,None,Precision,[]

In [ ]:
products.shape

(112590, 8)

In [ ]:
products["text"] = (
    products["title"].fillna("") + " " +
    products["features"].fillna("").astype(str) + " " +
    products["description"].fillna("").astype(str) + " " +
    products["categories"].fillna("").astype(str)
)

products[["title", "text"]].head()

,title,text
0,"Howard LC0008 Leather Conditioner, 8-Ounce (4-...","Howard LC0008 Leather Conditioner, 8-Ounce (4-..."
1,Yes to Tomatoes Detoxifying Charcoal Cleanser ...,Yes to Tomatoes Detoxifying Charcoal Cleanser ...
2,Eye Patch Black Adult with Tie Band (6 Per Pack),Eye Patch Black Adult with Tie Band (6 Per Pac...
3,"Tattoo Eyebrow Stickers, Waterproof Eyebrow, 4...","Tattoo Eyebrow Stickers, Waterproof Eyebrow, 4..."
4,Precision Plunger Bars for Cartridge Grips – 9...,Precision Plunger Bars for Cartridge Grips – 9...

In [ ]:
products["text"] = products["text"].str.lower()
products["text"] = products["text"].str.replace(r"\s+", " ", regex=True)

products[["title", "text"]].head()

,title,text
0,"Howard LC0008 Leather Conditioner, 8-Ounce (4-...","howard lc0008 leather conditioner, 8-ounce (4-..."
1,Yes to Tomatoes Detoxifying Charcoal Cleanser ...,yes to tomatoes detoxifying charcoal cleanser ...
2,Eye Patch Black Adult with Tie Band (6 Per Pack),eye patch black adult with tie band (6 per pac...
3,"Tattoo Eyebrow Stickers, Waterproof Eyebrow, 4...","tattoo eyebrow stickers, waterproof eyebrow, 4..."
4,Precision Plunger Bars for Cartridge Grips – 9...,precision plunger bars for cartridge grips – 9...

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=20000
)

tfidf_matrix = tfidf.fit_transform(products["text"])

print(tfidf_matrix.shape)

(112590, 20000)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend_products(product_name, n=5):

    # Find products matching the search term
    matches = products[
        products["title"].str.contains(
            product_name,
            case=False,
            na=False
        )
    ]

    # Check if the product exists
    if matches.empty:
        print("Product not found.")
        return

    # Get the index of the first matching product
    idx = matches.index[0]

    # Calculate similarity with all products
    scores = cosine_similarity(
        tfidf_matrix[idx],
        tfidf_matrix
    ).flatten()

    # Sort products by similarity score
    similar_indices = scores.argsort()[::-1]

    # Remove the selected product itself
    similar_indices = [
        i for i in similar_indices
        if i != idx
    ][:n]

    # Create recommendation result
    result = products.iloc[similar_indices][
        [
            "title",
            "average_rating",
            "price",
            "store"
        ]
    ].copy()

    # Add similarity score
    result["similarity_score"] = scores[similar_indices]

    return result

In [ ]:
recommend_products("shampoo", 5)

,title,average_rating,price,store,similarity_score
26364,John Frieda Frizz Ease Daily Nourishment Moist...,4.1,None,John Frieda,0.551955
86983,John Frieda Frizz-Ease Dream Curls Conditioner...,4.4,None,John Frieda,0.519100
71772,John Frieda Frizz-Ease Heat Defeat Protective ...,5.0,None,None,0.502667
63993,John Frieda Frizz-Ease Flawlessly Straight Sha...,4.5,24.89,John Frieda,0.498325
101841,"John Frieda Frizz Ease KeraFlex Hairspray, Fle...",5.0,None,John Frieda,0.480719

In [ ]:
result = recommend_products("shampoo", 5)

result

,title,average_rating,price,store,similarity_score
26364,John Frieda Frizz Ease Daily Nourishment Moist...,4.1,None,John Frieda,0.551955
86983,John Frieda Frizz-Ease Dream Curls Conditioner...,4.4,None,John Frieda,0.519100
71772,John Frieda Frizz-Ease Heat Defeat Protective ...,5.0,None,None,0.502667
63993,John Frieda Frizz-Ease Flawlessly Straight Sha...,4.5,24.89,John Frieda,0.498325
101841,"John Frieda Frizz Ease KeraFlex Hairspray, Fle...",5.0,None,John Frieda,0.480719

In [ ]:
result[["title", "price", "average_rating", "similarity_score"]]

,title,price,average_rating,similarity_score
26364,John Frieda Frizz Ease Daily Nourishment Moist...,None,4.1,0.551955
86983,John Frieda Frizz-Ease Dream Curls Conditioner...,None,4.4,0.519100
71772,John Frieda Frizz-Ease Heat Defeat Protective ...,None,5.0,0.502667
63993,John Frieda Frizz-Ease Flawlessly Straight Sha...,24.89,4.5,0.498325
101841,"John Frieda Frizz Ease KeraFlex Hairspray, Fle...",None,5.0,0.480719

In [ ]:
result = recommend_products("shampoo", 5)

result

,title,average_rating,price,store,similarity_score
26364,John Frieda Frizz Ease Daily Nourishment Moist...,4.1,None,John Frieda,0.551955
86983,John Frieda Frizz-Ease Dream Curls Conditioner...,4.4,None,John Frieda,0.519100
71772,John Frieda Frizz-Ease Heat Defeat Protective ...,5.0,None,None,0.502667
63993,John Frieda Frizz-Ease Flawlessly Straight Sha...,4.5,24.89,John Frieda,0.498325
101841,"John Frieda Frizz Ease KeraFlex Hairspray, Fle...",5.0,None,John Frieda,0.480719

In [ ]:
print(result.columns)

Index(['title', 'average_rating', 'price', 'store', 'similarity_score'], dtype='object')

In [ ]:
result[[
    "title",
    "price",
    "average_rating",
    "similarity_score"
]]

,title,price,average_rating,similarity_score
26364,John Frieda Frizz Ease Daily Nourishment Moist...,None,4.1,0.551955
86983,John Frieda Frizz-Ease Dream Curls Conditioner...,None,4.4,0.519100
71772,John Frieda Frizz-Ease Heat Defeat Protective ...,None,5.0,0.502667
63993,John Frieda Frizz-Ease Flawlessly Straight Sha...,24.89,4.5,0.498325
101841,"John Frieda Frizz Ease KeraFlex Hairspray, Fle...",None,5.0,0.480719

In [ ]:
def recommend_products(product_name, n=5):

    # Find products matching the search term
    matches = products[
        products["title"].str.contains(
            product_name,
            case=False,
            na=False
        )
    ]

    if matches.empty:
        print("Product not found.")
        return

    # Get the first matching product
    idx = matches.index[0]

    # Calculate similarity with all products
    similarity_scores = cosine_similarity(
        tfidf_matrix[idx],
        tfidf_matrix
    ).flatten()

    # Create a copy of the product data
    result = products.copy()

    # Add similarity score
    result["similarity_score"] = similarity_scores

    # Normalize ratings between 0 and 1
    result["rating_score"] = result["average_rating"] / 5

    # Create a combined recommendation score
    result["recommendation_score"] = (
        0.7 * result["similarity_score"] +
        0.3 * result["rating_score"]
    )

    # Remove the selected product
    result = result.drop(index=idx)

    # Sort by recommendation score
    result = result.sort_values(
        by="recommendation_score",
        ascending=False
    )

    # Return top recommendations
    return result.head(n)[
        [
            "title",
            "price",
            "average_rating",
            "similarity_score",
            "recommendation_score"
        ]
    ]

In [ ]:
recommend_products("shampoo", 5)

,title,price,average_rating,similarity_score,recommendation_score
71772,John Frieda Frizz-Ease Heat Defeat Protective ...,None,5.0,0.502667,0.651867
101841,"John Frieda Frizz Ease KeraFlex Hairspray, Fle...",None,5.0,0.480719,0.636503
26364,John Frieda Frizz Ease Daily Nourishment Moist...,None,4.1,0.551955,0.632368
86983,John Frieda Frizz-Ease Dream Curls Conditioner...,None,4.4,0.519100,0.627370
25121,John Frieda Frizz Ease Moisture Barrier Hairsp...,None,5.0,0.460479,0.622336

In [ ]:
!pip install streamlit pyngrok

Collecting streamlit
  Downloading streamlit-1.62.0-py3-none-any.whl.metadata (10 kB)
Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (8.4.2)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.13/dist-packages (from streamlit) (26.3)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (1.6.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.52.3)
Requirement already satisfied: httptools<1,>=0.6.3 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.13/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.13/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.24.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.18)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2026.7.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.62.0-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 76.5 MB/s eta 0:00:00
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Downloading pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 88.3 MB/s eta 0:00:00
Installing collected packages: pyngrok, pydeck, streamlit
Successfully installed pydeck-0.9.3 pyngrok-8.1.2 streamlit-1.62.0

In [ ]:
%%writefile app.py

import streamlit as st
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity


st.set_page_config(
    page_title="Product Recommendation System",
    page_icon="🛍️",
    layout="wide"
)


st.title("🛍️ Product Recommendation System")
st.write("Find products similar to your selected product.")


def recommend_products(product_name, n=5):

    matches = products[
        products["title"].str.contains(
            product_name,
            case=False,
            na=False
        )
    ]

    if matches.empty:
        return pd.DataFrame()

    idx = matches.index[0]

    similarity_scores = cosine_similarity(
        tfidf_matrix[idx],
        tfidf_matrix
    ).flatten()

    result = products.copy()

    result["similarity_score"] = similarity_scores
    result["rating_score"] = result["average_rating"] / 5

    result["recommendation_score"] = (
        0.7 * result["similarity_score"] +
        0.3 * result["rating_score"]
    )

    result = result.drop(index=idx)

    result = result.sort_values(
        by="recommendation_score",
        ascending=False
    )

    return result.head(n)


product_name = st.text_input(
    "Enter a product name",
    placeholder="Example: shampoo"
)


if st.button("Get Recommendations"):

    if product_name:

        recommendations = recommend_products(
            product_name,
            5
        )

        if recommendations.empty:
            st.warning("Product not found.")

        else:
            st.subheader("Recommended Products")

            for _, product in recommendations.iterrows():

                st.write("###", product["title"])

                col1, col2, col3 = st.columns(3)

                with col1:
                    st.write(
                        f"**Price:** {product['price']}"
                    )

                with col2:
                    st.write(
                        f"**Rating:** {product['average_rating']}"
                    )

                with col3:
                    st.write(
                        f"**Similarity:** "
                        f"{product['similarity_score']:.2f}"
                    )

                st.divider()

    else:
        st.info("Please enter a product name.")

Writing app.py

In [ ]:
import pickle

with open("products.pkl", "wb") as file:
    pickle.dump(products, file)

with open("tfidf_matrix.pkl", "wb") as file:
    pickle.dump(tfidf_matrix, file)

print("Model files saved successfully.")

Model files saved successfully.

In [ ]:
import os

print(os.path.exists("app.py"))
print(os.path.exists("products.pkl"))
print(os.path.exists("tfidf_matrix.pkl"))

True
True
True

In [ ]:
%%writefile app.py

import streamlit as st
import pandas as pd
import pickle
from sklearn.metrics.pairwise import cosine_similarity


st.set_page_config(
    page_title="Product Recommendation System",
    page_icon="🛍️",
    layout="wide"
)


# Load saved data
with open("products.pkl", "rb") as file:
    products = pickle.load(file)

with open("tfidf_matrix.pkl", "rb") as file:
    tfidf_matrix = pickle.load(file)


def recommend_products(product_name, n=5):

    matches = products[
        products["title"].str.contains(
            product_name,
            case=False,
            na=False
        )
    ]

    if matches.empty:
        return pd.DataFrame()

    idx = matches.index[0]

    similarity_scores = cosine_similarity(
        tfidf_matrix[idx],
        tfidf_matrix
    ).flatten()

    result = products.copy()

    result["similarity_score"] = similarity_scores
    result["rating_score"] = result["average_rating"] / 5

    result["recommendation_score"] = (
        0.7 * result["similarity_score"] +
        0.3 * result["rating_score"]
    )

    result = result.drop(index=idx)

    result = result.sort_values(
        by="recommendation_score",
        ascending=False
    )

    return result.head(n)


# App interface
st.title("🛍️ Product Recommendation System")
st.write(
    "Enter a product name to find similar products."
)


product_name = st.text_input(
    "Enter a product name",
    placeholder="Example: shampoo"
)


if st.button("Get Recommendations"):

    if product_name:

        recommendations = recommend_products(
            product_name,
            5
        )

        if recommendations.empty:

            st.warning("Product not found.")

        else:

            st.subheader("Recommended Products")

            for _, product in recommendations.iterrows():

                st.write(
                    f"### {product['title']}"
                )

                col1, col2, col3 = st.columns(3)

                with col1:
                    st.write(
                        f"**Price:** {product['price']}"
                    )

                with col2:
                    st.write(
                        f"**Rating:** {product['average_rating']}"
                    )

                with col3:
                    st.write(
                        f"**Similarity:** "
                        f"{product['similarity_score']:.2f}"
                    )

                st.divider()

    else:

        st.info("Please enter a product name.")

Overwriting app.py

In [ ]:
!streamlit run app.py &> streamlit.log &

In [ ]:
!cat streamlit.log

In [ ]:
from pyngrok import ngrok

ngrok.set_auth_token("3IH1HCE6ySbU0erVs4J8Uyl5hHq_3nb7x1i6vyU6W7o9hCF1w")

print("ngrok authentication configured successfully.")

ngrok authentication configured successfully.

In [ ]:
public_url = ngrok.connect(8501)

print(public_url)

NgrokTunnel: "https://statue-politely-retired.ngrok-free.dev" -> "http://localhost:8501"